// Triangulated Veracity Score — the single TypeScript implementation.
// Mirrors Alex1.py::calculate_veracity_score_semantic exactly (the Python
// function is canonical; tests/tvs.test.ts checks parity against a fixture
// generated by the Python code).
//
//   S_sem  = 30 + 70 * mean(top-3 cosine similarities summary↔source)
//   F_dom  = 1.00 (≥5 domains) | 0.95 (4) | 0.85 (3) | 0.72 (2) | 0.60 (≤1)
//   F_coh  = 0.70 + 0.30 * mean(pairwise source similarity, upper triangle)
//   V      = clamp(int(S_sem * F_dom * F_coh), 5, 99)

import type { ScoreBreakdown } from "./types";

const AGGREGATOR_HOSTS = new Set([
  "news.google.com", "google.com", "r.search.yahoo.com", "news.search.yahoo.com",
  "bing.com", "duckduckgo.com", "msn.com", "feedproxy.google.com",
]);

/** 'https://www.reuters.com/x' -> 'reuters.com'; '' when unparsable. */
export function registrableDomain(url: string): string {
  try {
    const host = new URL(url).hostname.toLowerCase();
    return host.replace(/^(www\.|news\.|edition\.|feeds\.|amp\.|m\.)/, "");
  } catch {
    return "";
  }
}

export function isAggregator(url: string): boolean {
  const host = registrableDomain(url);
  return host === "" || AGGREGATOR_HOSTS.has(host) || host.endsWith(".google.com");
}

/** Domain that counts as an independent source; '' for aggregator/redirect hosts. */
export function publisherDomain(url: string, publisherUrl?: string | null): string {
  for (const candidate of [publisherUrl, url]) {
    if (!candidate) continue;
    const domain = registrableDomain(candidate);
    if (domain && !isAggregator(candidate)) return domain;
  }
  return "";
}

export function domainFactor(nDomains: number): number {
  if (nDomains >= 5) return 1.0;
  if (nDomains === 4) return 0.95;
  if (nDomains === 3) return 0.85;
  if (nDomains === 2) return 0.72;
  return 0.6;
}

export function semanticScore(similarities: number[]): { semanticScore: number; avgSimilarity: number } {
  const top = [...similarities].sort((a, b) => b - a).slice(0, 3);
  const avg = top.length ? top.reduce((s, v) => s + v, 0) / top.length : 0;
  return { semanticScore: 30 + avg * 70, avgSimilarity: avg };
}

export function coherenceFactor(pairwiseUpperTriangle: number[]): { coherenceFactor: number; sourceCoherence: number } {
  // A single source cannot agree with anyone: neutral 0.5, like the Python code.
  const mean = pairwiseUpperTriangle.length
    ? pairwiseUpperTriangle.reduce((s, v) => s + v, 0) / pairwiseUpperTriangle.length
    : 0.5;
  return { coherenceFactor: 0.7 + mean * 0.3, sourceCoherence: mean };
}

export function clampScore(raw: number): number {
  return Math.min(99, Math.max(5, Math.trunc(raw)));
}

/**
 * Full breakdown from per-source evidence.
 * @param similarities  cosine(summary, source_i) for every source
 * @param sources       one identity per source (domain or name key); '' = unknown
 * @param pairwise      upper triangle of the source×source similarity matrix
 */
export function calculateVeracityScore(
  similarities: number[],
  sources: string[],
  pairwise: number[],
): ScoreBreakdown {
  const { semanticScore: sem, avgSimilarity } = semanticScore(similarities);
  const domains = Array.from(new Set(sources.filter(Boolean))).sort();
  const dFactor = domainFactor(domains.length);
  const { coherenceFactor: cFactor, sourceCoherence } = coherenceFactor(pairwise);
  return {
    finalScore: clampScore(sem * dFactor * cFactor),
    semanticScore: Math.round(sem * 100) / 100,
    avgSimilarity: Math.round(avgSimilarity * 10000) / 10000,
    domainFactor: dFactor,
    nDomains: domains.length,
    domains,
    coherenceFactor: Math.round(cFactor * 10000) / 10000,
    sourceCoherence: Math.round(sourceCoherence * 10000) / 10000,
  };
}

/**
 * Rebuilds the upper triangle from the per-article "agreement with every
 * other source" rows the exporter writes (row i has N-1 entries, self skipped).
 */
export function upperTriangleFromRows(rows: number[][]): number[] {
  const n = rows.length;
  const values: number[] = [];
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const idx = j > i ? j - 1 : j;
      const v = rows[i]?.[idx];
      if (typeof v === "number") values.push(v);
    }
  }
  return values;
}

/** Human-readable consensus tier used by the report and the UI. */
export function consensusLabel(nDomains: number): "STRONG" | "GOOD" | "MODERATE" | "WEAK" | "SINGLE-SOURCE" {
  if (nDomains >= 5) return "STRONG";
  if (nDomains === 4) return "GOOD";
  if (nDomains === 3) return "MODERATE";
  if (nDomains === 2) return "WEAK";
  return "SINGLE-SOURCE";
}

/** Verification-confidence band (never a claim about factual truth). */
export function confidenceBand(score: number): { label: string; tone: "high" | "medium" | "low" } {
  if (score >= 80) return { label: "High verification confidence", tone: "high" };
  if (score >= 75) return { label: "Moderate verification confidence", tone: "medium" };
  if (score > 50) return { label: "Low confidence — review sources", tone: "medium" };
  return { label: "Flagged — weak or contradictory sourcing", tone: "low" };
}
