"use client";

import { useCallback, useEffect, useRef, useState } from "react";

import type { PipelineMode, PipelineTopic, QualityReport, StressTestCase } from "@/lib/types";

export interface ExportMeta {
  generatedAt: string | null;
  generatedBy: string | null;
  qualityReport: QualityReport | null;
  topics: string[];
}

interface UsePipelineDataOptions {
  /** Poll interval for /api/pipeline/version while idle (ms). */
  pollMs?: number;
  /** Faster polling while a pipeline job is running (ms). */
  activePollMs?: number;
  /** Whether a job is running (tightens the polling). */
  jobRunning?: boolean;
}

/**
 * Loads the pipeline export for the dashboard: topic list + quality report,
 * the selected topic's evidence, the stress-test fixture, and hot-refresh
 * when public/osint_output.json changes on disk (batch or streaming run).
 */
export function usePipelineData({ pollMs = 30000, activePollMs = 5000, jobRunning = false }: UsePipelineDataOptions = {}) {
  const [mode, setMode] = useState<PipelineMode>("osint");
  const [meta, setMeta] = useState<ExportMeta>({ generatedAt: null, generatedBy: null, qualityReport: null, topics: [] });
  const [selectedTopic, setSelectedTopic] = useState<string | null>(null);
  const [topicData, setTopicData] = useState<PipelineTopic | null>(null);
  const [stressCases, setStressCases] = useState<StressTestCase[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState("Ready.");
  const [exportMissing, setExportMissing] = useState(false);

  const abortRef = useRef<AbortController | null>(null);
  const selectedRef = useRef<string | null>(null);
  useEffect(() => {
    selectedRef.current = selectedTopic;
  }, [selectedTopic]);

  const loadMeta = useCallback(async (): Promise<ExportMeta | null> => {
    try {
      const res = await fetch("/api/pipeline", { cache: "no-store" });
      const json = await res.json();
      if (!res.ok || !json.success) {
        setExportMissing(res.status === 503);
        if (res.status === 503) setError(json.error);
        return null;
      }
      const next: ExportMeta = {
        generatedAt: json.generatedAt ?? null,
        generatedBy: json.generatedBy ?? null,
        qualityReport: json.qualityReport ?? null,
        topics: Array.isArray(json.topics) ? json.topics : [],
      };
      setMeta(next);
      setExportMissing(false);
      return next;
    } catch (e) {
      console.warn("export metadata unavailable", e);
      return null;
    }
  }, []);

  const loadTopic = useCallback(async (topic: string) => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setLoading(true);
    setError(null);
    setStatus(`Loading evidence for "${topic}"...`);
    try {
      const res = await fetch("/api/pipeline", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: controller.signal,
        body: JSON.stringify({ mode: "osint", topic }),
      });
      const json = await res.json();
      if (controller.signal.aborted) return;
      if (!res.ok || !json.success) {
        setTopicData(null);
        setExportMissing(res.status === 503);
        throw new Error(json.error || `Request failed (${res.status}).`);
      }
      setTopicData(json as PipelineTopic);
      setStatus(json.generatedAt ? `Export from ${String(json.generatedAt).replace("T", " ")} loaded.` : "Evidence loaded.");
    } catch (e) {
      if ((e as Error)?.name === "AbortError" || controller.signal.aborted) return;
      setError((e as Error).message || "Unable to contact the pipeline API.");
      setStatus("Load error.");
    } finally {
      if (!controller.signal.aborted) setLoading(false);
    }
  }, []);

  const loadStressCases = useCallback(async () => {
    setLoading(true);
    setError(null);
    setStatus("Loading the TVS stress-test fixture (real SBERT evidence)...");
    try {
      const res = await fetch("/api/pipeline", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mode: "stress_test" }),
      });
      const json = await res.json();
      if (!res.ok || !json.success) throw new Error(json.error || "Stress-test fixture unavailable.");
      setStressCases(json.testCases as StressTestCase[]);
      setStatus(json.generatedBy ? `Fixture generated by ${json.generatedBy}.` : "Fixture loaded.");
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }, []);

  // Initial load: metadata, then first topic.
  useEffect(() => {
    let active = true;
    (async () => {
      const next = await loadMeta();
      if (!active) return;
      if (next && next.topics.length > 0) {
        setSelectedTopic((current) => current ?? next.topics[0]);
      } else {
        setLoading(false);
      }
    })();
    return () => {
      active = false;
    };
  }, [loadMeta]);

  // Mode / topic changes drive the fetches (scheduled: the effect body must
  // not setState synchronously).
  useEffect(() => {
    const timer = setTimeout(() => {
      if (mode === "benchmark") {
        setLoading(false);          // the Benchmark panel loads its own data
        setError(null);
        setStatus("Benchmark results (experiments/results).");
      } else if (mode === "stress_test") {
        loadStressCases();
      } else if (selectedTopic) {
        loadTopic(selectedTopic);
      }
    }, 0);
    return () => clearTimeout(timer);
  }, [mode, selectedTopic, loadTopic, loadStressCases]);

  // Hot refresh: poll the export's mtime; reload metadata + current topic on change.
  useEffect(() => {
    let lastVersion: number | null = null;
    const interval = setInterval(async () => {
      try {
        const res = await fetch("/api/pipeline/version", { cache: "no-store" });
        if (!res.ok) return;
        const json = await res.json();
        if (typeof json.version !== "number" || json.version === 0) return;
        if (lastVersion === null) {
          lastVersion = json.version;
          return;
        }
        if (json.version !== lastVersion) {
          lastVersion = json.version;
          setStatus("Fresh pipeline export detected — refreshing...");
          const next = await loadMeta();
          if (mode === "osint") {
            const current = selectedRef.current;
            if (next && current && !next.topics.includes(current)) setSelectedTopic(next.topics[0] ?? null);
            else if (current) loadTopic(current);
          }
        }
      } catch {
        // polling is best-effort
      }
    }, jobRunning ? activePollMs : pollMs);
    return () => clearInterval(interval);
  }, [mode, jobRunning, pollMs, activePollMs, loadMeta, loadTopic]);

  const refresh = useCallback(async () => {
    await loadMeta();
    if (mode === "osint" && selectedRef.current) await loadTopic(selectedRef.current);
  }, [mode, loadMeta, loadTopic]);

  return {
    mode, setMode,
    meta, exportMissing,
    selectedTopic, setSelectedTopic,
    topicData, stressCases,
    loading, error, status, setStatus,
    refresh,
  };
}
